services:
  ui:
    build:
      context: app
      dockerfile: ./Dockerfile
    ports: 
      - "4173:4173"
  api:
    build:
      context: api
      dockerfile: ./Dockerfile
    ports: 
      - "7080:7080"
    env_file:
      - ./api/src/Db/db.env
  db:
    build:
      context: db
      dockerfile: ./Dockerfile
    ports:
      - "5432:5432"
    env_file:
      - ./api/src/Db/db.env
    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  postgis_data:
