kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: db
  namespace: a3e022-dev
  uid: ed94d995-c4d7-4735-928a-3d62f50e6b26
  resourceVersion: '9708989699'
  generation: 41
  creationTimestamp: '2024-03-14T17:40:11Z'
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps.openshift.io/v1","kind":"DeploymentConfig","metadata":{"annotations":{},"name":"api","namespace":"a3e022-dev"},"spec":{"replicas":1,"selector":{"app":"api"},"strategy":{"recreateParams":{"timeoutSeconds":600},"type":"Recreate"},"template":{"metadata":{"labels":{"app":"api"}},"spec":{"affinity":{"podAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"podAffinityTerm":{"labelSelector":{"matchLabels":{"postgres-operator.crunchydata.com/cluster":"invasivesbci-db","postgres-operator.crunchydata.com/role":"pgbouncer"}},"topologyKey":"kubernetes.io/hostname"},"weight":1}]}},"containers":[{"env":[{"name":"NODE_OPTIONS","value":"--max-old-space-size=6500"}],"image":"image-registry.openshift-image-registry.svc:5000/7068ad-tools/invasivesbci-api-dockerized@sha256:b175c9e1ab43dd076b0ec2d874925dc12cb80bb6b120e5bb36f77bdc9c0bf85f","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":2,"httpGet":{"path":"/api-docs","port":7080,"scheme":"HTTP"},"periodSeconds":30,"successThreshold":1,"timeoutSeconds":90},"name":"api","ports":[{"containerPort":7080,"protocol":"TCP"}],"readinessProbe":{"failureThreshold":1,"httpGet":{"path":"/api-docs","port":7080,"scheme":"HTTP"},"initialDelaySeconds":5,"periodSeconds":3,"successThreshold":1,"timeoutSeconds":1},"resources":{"limits":{"cpu":"1","memory":"1Gi"},"requests":{"cpu":"500m","memory":"256Mi"}},"startupProbe":{"failureThreshold":45,"httpGet":{"path":"/api-docs","port":7080,"scheme":"HTTP"},"periodSeconds":2,"successThreshold":1,"timeoutSeconds":1},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}},"triggers":[{"imageChangeParams":{"automatic":true,"containerNames":["api"],"from":{"kind":"ImageStreamTag","name":"api:latest","namespace":"a3e022-tools"}},"type":"ImageChange"},{"type":"ConfigChange"}]},"status":{"availableReplicas":2,"conditions":[{"lastTransitionTime":"2024-03-13T20:55:00Z","lastUpdateTime":"2024-03-13T20:55:03Z","message":"replication
      controller \"invasivesbci-api-dev-deploy-1886\" successfully rolled
      out","reason":"NewReplicationControllerAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2024-03-14T00:11:44Z","lastUpdateTime":"2024-03-14T00:11:44Z","message":"Deployment
      config has minimum
      availability.","status":"True","type":"Available"}],"details":{"causes":[{"imageTrigger":{"from":{"kind":"DockerImage","name":"image-registry.openshift-image-registry.svc:5000/7068ad-tools/invasivesbci-api-dockerized@sha256:b175c9e1ab43dd076b0ec2d874925dc12cb80bb6b120e5bb36f77bdc9c0bf85f"}},"type":"ImageChange"}],"message":"image
      change"},"latestVersion":1886,"observedGeneration":2641,"readyReplicas":2,"replicas":2,"unavailableReplicas":0,"updatedReplicas":2}}
  managedFields:
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: '2024-03-14T17:40:11Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
        'f:spec':
          'f:selector':
            .: {}
            'f:app': {}
          'f:strategy':
            'f:activeDeadlineSeconds': {}
            'f:recreateParams':
              .: {}
              'f:timeoutSeconds': {}
            'f:type': {}
          'f:template':
            .: {}
            'f:metadata':
              .: {}
              'f:creationTimestamp': {}
              'f:labels':
                .: {}
                'f:app': {}
            'f:spec':
              .: {}
              'f:affinity':
                .: {}
                'f:podAffinity':
                  .: {}
                  'f:preferredDuringSchedulingIgnoredDuringExecution': {}
              'f:containers':
                .: {}
                'k:{"name":"api"}':
                  'f:startupProbe':
                    .: {}
                    'f:failureThreshold': {}
                    'f:httpGet':
                      .: {}
                      'f:path': {}
                      'f:port': {}
                      'f:scheme': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:timeoutSeconds': {}
                  'f:terminationMessagePolicy': {}
                  .: {}
                  'f:resources':
                    .: {}
                    'f:limits':
                      .: {}
                      'f:memory': {}
                    'f:requests':
                      .: {}
                      'f:memory': {}
                  'f:livenessProbe':
                    .: {}
                    'f:failureThreshold': {}
                    'f:httpGet':
                      .: {}
                      'f:path': {}
                      'f:port': {}
                      'f:scheme': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:timeoutSeconds': {}
                  'f:env':
                    .: {}
                    'k:{"name":"NODE_OPTIONS"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                  'f:readinessProbe':
                    .: {}
                    'f:failureThreshold': {}
                    'f:httpGet':
                      .: {}
                      'f:path': {}
                      'f:port': {}
                      'f:scheme': {}
                    'f:initialDelaySeconds': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:timeoutSeconds': {}
                  'f:terminationMessagePath': {}
                  'f:imagePullPolicy': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":7080,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:name': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
    - manager: Mozilla
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: '2024-03-14T20:15:13Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:replicas': {}
          'f:template':
            'f:spec':
              'f:containers':
                'k:{"name":"api"}':
                  'f:resources':
                    'f:limits':
                      'f:cpu': {}
                    'f:requests':
                      'f:cpu': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: '2024-04-11T17:06:37Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:spec':
              'f:containers':
                'k:{"name":"api"}':
                  'f:image': {}
          'f:triggers': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: '2024-04-11T17:14:18Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:details':
            .: {}
            'f:causes': {}
            'f:message': {}
          'f:latestVersion': {}
          'f:observedGeneration': {}
          'f:replicas': {}
          'f:unavailableReplicas': {}
          'f:updatedReplicas': {}
      subresource: status
spec:
  strategy:
    type: Recreate
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - db
        from:
          kind: ImageStreamTag
          namespace: a3e022-tools
          name: 'db:latest'
        lastTriggeredImage: >-
          image-registry.openshift-image-registry.svc:5000/a3e022-tools/api@sha256:61af32c73837ac9f8c088340ba19f4331f4da299d01555af9678fa7f6a766eb5
    - type: ConfigChange
  replicas: 0
  revisionHistoryLimit: 10
  test: false
  selector:
    app: db
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: db
    spec:
      containers:
        - resources:
            limits:
              cpu: 300m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /api-docs
              port: 7080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 1
          terminationMessagePath: /dev/termination-log
          name: db
          livenessProbe:
            httpGet:
              path: /api-docs
              port: 7080
              scheme: HTTP
            timeoutSeconds: 90
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 2
          env:
            - name: NODE_OPTIONS
              value: '--max-old-space-size=6500'
          ports:
            - containerPort: 7080
              protocol: TCP
          imagePullPolicy: Always
          startupProbe:
            httpGet:
              path: /api-docs
              port: 7080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 2
            successThreshold: 1
            failureThreshold: 45
          terminationMessagePolicy: File
          image: >-
            image-registry.openshift-image-registry.svc:5000/a3e022-tools/api@sha256:61af32c73837ac9f8c088340ba19f4331f4da299d01555af9678fa7f6a766eb5
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    postgres-operator.crunchydata.com/cluster: invasivesbci-db
                    postgres-operator.crunchydata.com/role: pgbouncer
                topologyKey: kubernetes.io/hostname
      schedulerName: default-scheduler
status:
  latestVersion: 18
  observedGeneration: 41
  replicas: 0
  updatedReplicas: 0
  availableReplicas: 0
  unavailableReplicas: 0
  details:
    message: image change
    causes:
      - type: ImageChange
        imageTrigger:
          from:
            kind: DockerImage
            name: >-
              image-registry.openshift-image-registry.svc:5000/a3e022-tools/api@sha256:61af32c73837ac9f8c088340ba19f4331f4da299d01555af9678fa7f6a766eb5
  conditions:
    - type: Available
      status: 'False'
      lastUpdateTime: '2024-04-11T17:06:40Z'
      lastTransitionTime: '2024-04-11T17:06:40Z'
      message: Deployment config does not have minimum availability.
    - type: Progressing
      status: 'False'
      lastUpdateTime: '2024-04-11T17:14:18Z'
      lastTransitionTime: '2024-04-11T17:14:18Z'
      reason: ProgressDeadlineExceeded
      message: replication controller "api-18" has failed progressing
